### ISSUE TITLE
Old-style language tags is too vague

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#159] opened 2017-08-03 15:31 UTC
https://tc39.github.io/ecma402/#sec-internal-slots:
> For locales that in current usage would include a script subtag (such as Chinese locales), old-style language tags without script subtags must be included such that, for example, requests for "zh-TW" and "zh-HK" lead to output in traditional Chinese rather than the default simplified Chinese.

This description is pretty vague and doesn't really explain how to identify "old-style language tags".

SpiderMonkey has this fixed list of old-style language tags (http://searchfox.org/mozilla-central/rev/f0e4ae5f8c40ba742214e89aba3f554da0b89a33/js/src/builtin/Intl.js#587-596), but to me it's not really clear if this list is complete or has too many/too few entries.

**Comment by anba** [comment] 2017-08-03 16:00
I think a more concrete definition could avoid these *slightly* inconsistent and also confusing results from a user's point of view.

```js
function printDate(locale) {
    var date = new Date(Date.UTC(2017, 8-1, 3));
    var dtf = new Intl.DateTimeFormat(locale, {year: "numeric", month: "2-digit", day: "2-digit", weekday: "long", timeZoneName: "long", timeZone: "Europe/Berlin"});
    print(`${locale} resolved to ${dtf.resolvedOptions().locale}: ${dtf.format(date)}`);
}

for (let locale of ["pa-PK", "zh-HK", "uz-AF"])
    printDate(locale);

// With scripts per cldr30/supplemental/likelySubtags.xml
for (let locale of ["pa-Arab-PK", "zh-Hant-HK", "uz-Arab-AF"])
    printDate(locale);
```

SpiderMonkey (built today, ICU59)
```text
pa-PK resolved to pa-PK: ۲۰۱۷-۰۸-۰۳, جمعرات GMT+۰۲:۰۰
zh-HK resolved to zh-HK: 2017年08月03日星期四 中歐夏令時間
uz-AF resolved to uz: payshanba, 03/08/2017, Markaziy Yevropa yozgi vaqti
pa-Arab-PK resolved to pa-Arab-PK: ۲۰۱۷-۰۸-۰۳, جمعرات GMT+۰۲:۰۰
zh-Hant-HK resolved to zh-Hant-HK: 2017年08月03日星期四 中歐夏令時間
uz-Arab-AF resolved to uz-Arab-AF: AP ۱۳۹۶-۰۵-۱۲, پنجشنبه GMT+۰۲:۰۰
```

V8 (built today, ICU59 - no idea why the time zone is localized in my user language...)
```text
pa-PK resolved to pa: 2017-08-03, Thu Mitteleuropäische Sommerzeit
zh-HK resolved to zh-HK: 2017年08月03日星期四 中歐夏令時間
uz-AF resolved to uz: 2017-08-03, Thu Mitteleuropäische Sommerzeit
pa-Arab-PK resolved to pa: 2017-08-03, Thu Mitteleuropäische Sommerzeit
zh-Hant-HK resolved to zh-Hant-HK: 2017年08月03日星期四 中歐夏令時間
uz-Arab-AF resolved to uz: 2017-08-03, Thu Mitteleuropäische Sommerzeit
```

JSC (built today, system ICU=ICU55)
```text
pa-PK resolved to pa: ਵੀਰਵਾਰ, 03/08/2017, ਮੱਧ ਯੂਰਪੀ ਗਰਮੀ-ਰੁੱਤ ਸਮਾਂ
zh-HK resolved to zh: 2017年08月03日星期四 中欧夏令时间
uz-AF resolved to uz: 2017-08-03, payshanba Markaziy Yevropa yozgi vaqti
pa-Arab-PK resolved to pa-Arab-PK: ۲۰۱۷-۰۸-۰۳, جمعرات GMT+۰۲:۰۰
zh-Hant-HK resolved to zh-Hant-HK: 2017年08月03日星期四 中歐夏令時間
uz-Arab-AF resolved to uz-Arab-AF: AP ۱۳۹۶-۰۵-۱۲, پنجشنبه GMT+۰۲:۰۰
```

**Comment by littledan** [comment] 2017-08-10 17:59
How do you think these tags should be resolved? Do you have an idea for more specific language?

cc @jungshik

**Comment by anba** [comment] 2017-08-10 19:16
> How do you think these tags should be resolved? Do you have an idea for more specific language?

I have trouble to find any source which explains how to identify the locales which should get these additional "old-style language tags without script subtags". If this rule only applies to the five locales used in SpiderMonkey, we should simply enumerate these locales in the spec.

**Comment by sffc** [comment] 2020-06-05 20:41
@FrankYFTang @jswalden @rkirsling  Thoughts on this?

**Comment by FrankYFTang** [comment] 2020-06-05 22:11
The information is very old. On Chrome m83 (ICU65) what I see is
```
pa-PK resolved to en-US: Thursday, 08/03/2017, Central European Summer Time
zh-HK resolved to zh-HK: 2017年08月03日星期四 中歐夏令時間
uz-AF resolved to en-US: Thursday, 08/03/2017, Central European Summer Time
pa-Arab-PK resolved to en-US: Thursday, 08/03/2017, Central European Summer Time
zh-Hant-HK resolved to zh-Hant-HK: 2017年08月03日星期四 中歐夏令時間
uz-Arab-AF resolved to en-US: Thursday, 08/03/2017, Central European Summer Time
```
Notice, 
1. on v8, there were a bug of resolvedOptions().locale which does not faithfully report what locale was resolved but got fixed about a year ago.
2. on v8, the default build filter out pa and uz locale for Chrome so what you see is the result of "default locale" now,

**Comment by sffc** [comment] 2020-06-05 23:28
Makes sense.  I agree.  "Old-style" means that it's more specific to write zh-Hant-HK, but we should map zh-HK to the same data.  I will close this issue.  Please re-open if there is further work to do.

**Comment by anba** [comment] 2020-06-06 06:54
Please reopen. The issue raised in <https://github.com/tc39/ecma402/issues/159#issue-247746804> is still not resolved.

**Comment by sffc** [comment] 2020-06-06 07:50
OK.

The way I interpret the text is, if you have a language+script+region locale ("new style"), you must also have entries for language+region without script ("old style").

Does that sound like a reasonable interpretation in order to make the spec text more clear?

**Comment by anba** [comment] 2020-06-06 09:02
I simply don't know if *old-style language tags* should be applied to all locales or just a certain subset. The linked SpiderMonkey source code was originally written by Norbert Lindenberg, so when he wrote:
> Certain old, commonly-used language tags that lack a script, are expected to nonetheless imply one.

it reads to me that it shouldn't apply to all locales.

---

This is the list of all locales which may need to be special-cased. (The majority of them aren't available in V8 due to missing data, so some care must be taken when writing test cases!)
<details>

```
az-Cyrl-AZ
az-Latn-AZ
bs-Cyrl-BA
bs-Latn-BA
ff-Adlm-BF
ff-Adlm-CM
ff-Adlm-GH
ff-Adlm-GM
ff-Adlm-GN
ff-Adlm-GW
ff-Adlm-LR
ff-Adlm-MR
ff-Adlm-NE
ff-Adlm-NG
ff-Adlm-SL
ff-Adlm-SN
ff-Latn-BF
ff-Latn-CM
ff-Latn-GH
ff-Latn-GM
ff-Latn-GN
ff-Latn-GW
ff-Latn-LR
ff-Latn-MR
ff-Latn-NE
ff-Latn-NG
ff-Latn-SL
ff-Latn-SN
ks-Arab-IN
mni-Beng-IN
pa-Arab-PK
pa-Guru-IN
sat-Olck-IN
sd-Arab-PK
sd-Deva-IN
shi-Latn-MA
shi-Tfng-MA
sr-Cyrl-BA
sr-Cyrl-ME
sr-Cyrl-RS
sr-Cyrl-XK
sr-Latn-BA
sr-Latn-ME
sr-Latn-RS
sr-Latn-XK
su-Latn-ID
uz-Arab-AF
uz-Cyrl-UZ
uz-Latn-UZ
vai-Latn-LR
vai-Vaii-LR
yue-Hans-CN
yue-Hant-HK
zh-Hans-CN
zh-Hans-HK
zh-Hans-MO
zh-Hans-SG
zh-Hant-HK
zh-Hant-MO
zh-Hant-TW
```

Generated by:
```java
import java.util.Arrays;
import java.util.stream.Collectors;
import com.ibm.icu.text.DateFormat;
import com.ibm.icu.util.ULocale;

public class OldStyleLanguageTags {
    public static void main(String[] args) {
        var supported = Arrays.stream(DateFormat.getAvailableULocales()).map(ULocale::toLanguageTag)
                .collect(Collectors.toSet());
        Arrays.stream(DateFormat.getAvailableULocales())
                .filter(loc -> !loc.getScript().isEmpty() && !loc.getCountry().isEmpty())
                .filter(loc -> !supported.contains(String.format("%s-%s", loc.getLanguage(), loc.getCountry())))
                .map(ULocale::toLanguageTag).forEach(System.out::println);
    }
}
```
</details>

The list contains `sr-Cyrl-ME` and `sr-Latn-ME`. So if we define *new style* as any locale containing a script subtag, `sr-ME` must also be supported as the corresponding *old style* locale. The next question is do we need to map `sr-ME` to `sr-Cyrl-ME` or to `sr-Latn-ME`? If we take likely-subtags data, `sr-ME` should be mapped to `sr-Latn-ME`:
```js
js> new Intl.Locale("sr-ME").maximize().toString()
"sr-Latn-ME"
```

But in JSC, SM, and V8:
```js
js> print(new Intl.DateTimeFormat("sr-ME",{localeMatcher: "lookup", timeZoneName:"long"}).format(0))         
31.12.1969. Северноамеричко пацифичко стандардно време
```

which is clearly not `sr-Latn-ME`.

JSC and SM report as the resolved locale:
```js
js> new Intl.DateTimeFormat("sr-ME",{localeMatcher: "lookup", timeZoneName:"long"}).resolvedOptions().locale
"sr"
```

whereas V8 reports:
```js
d8> new Intl.DateTimeFormat("sr-ME",{localeMatcher: "lookup", timeZoneName:"long"}).resolvedOptions().locale
"sr-ME"
```

**Comment by rkirsling** [comment] 2020-06-06 21:00
I'm also kind of confused about how much of this ICU is able to take care of. When I recently switched JSC to rely more directly on ICU for locale resolution, I [removed](https://github.com/WebKit/webkit/commit/901e43558b95d8bca57eeae6822a417a9ec101c1#diff-b6c9da7b170577e6c51862ac67b1dadfL158) these five special cases because I expected that they would be mapped automatically.

With ICU 64 (Catalina system ICU) this does not seem to be the case, but since I don't see these locales being called out explicitly in the V8 source, I was assuming that this was corrected in a more recent ICU version.

I do see that ICU marks, e.g, [zh_TW](https://github.com/unicode-org/icu/blob/master/icu4c/source/data/locales/zh_TW.txt) as an alias of zh_Hant_TW, but judging from the commit history, it seems like this goes back to ICU 58, so I'm pretty confused.

**Comment by FrankYFTang** [comment] 2020-06-08 23:02
The reason v8 show a cyrllic timezone on "sr-ME" I believe is due to a bug in data filter. See https://bugs.chromium.org/p/v8/issues/detail?id=10599 . The problem is some of the data source didn't get included during the build. I am trying to fix that now.

**Comment by sffc** [comment] 2020-06-08 23:02
I think the set of locales with an implied non-default script is implementation-dependent.  Likely subtags data is a good place to start if you want to implement it yourself without using ICU.

Side note: [ICU4C says that](https://github.com/unicode-org/icu/blob/maint/maint-67/icu4c/source/data/locales/sr_ME.txt) sr-ME should map to sr-Latn-ME, consistent with likely subtags.

**Comment by rkirsling** [comment] 2020-06-09 02:14
To partially answer my own question, I confirmed that even in ICU 67, `uloc_getAvailable` won't ever return `zh-TW` and friends. I'm perplexed as to how this is working in V8 right now (could there be a C vs. C++ API difference?).

**Comment by sffc** [comment] 2020-06-09 04:38
ICU 65+ has [uloc_openAvailableByType](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/uloc_8h.html#aeeabdb86b30d9b820f004a590f55020f), which gives you a list of locales that includes the alias locales like zh-TW.

**Comment by anba** [comment] 2020-06-09 12:53
ICU seems to use [this list](https://github.com/unicode-org/icu/blob/master/icu4c/source/data/icu-locale-deprecates.xml). Is that one generated or hand-written? (And why does the [collator list](https://github.com/unicode-org/icu/blob/master/icu4c/source/data/icu-coll-deprecates.xml) contain conflicting entries?)

**Comment by rkirsling** [comment] 2020-06-09 23:47
Similarly, do you know if there's any intention to have an uloc_openAvailableByType equivalent for Collator use?

**Comment by rkirsling** [comment] 2020-06-10 01:05
Also I believe it may be too naive to assume that an alias will exist for `xx-ZZ` just because `xx-Yyyy-ZZ` exists?

For instance, [ICU4C](https://github.com/unicode-org/icu/tree/master/icu4c/source/data/locales) has the following Fulah locales...
```
ff
ff-Adlm
ff-Adlm-{BF, CM, GH, GM, GN, GW, LR, MR, NE, NG, SL, SN}
ff-Latn
ff-Latn-{BF, CM, GH, GM, GN, GW, LR, MR, NE, NG, SL, SN}
ff-{CM, GN, MR, SN}
```
...which is to say that it lacks aliases `ff-{BF, GH, GM, GW, LR, NE, NG, SL}`.

**Comment by sffc** [comment] 2020-06-10 04:49
> ICU seems to use [this list](https://github.com/unicode-org/icu/blob/master/icu4c/source/data/icu-locale-deprecates.xml). Is that one generated or hand-written? (And why does the [collator list](https://github.com/unicode-org/icu/blob/master/icu4c/source/data/icu-coll-deprecates.xml) contain conflicting entries?)

It's manually maintained, but intended to be consistent with likely subtags. I have a bug to make it just pull from likely subtags, but it's been tricky to implement, so for now we're still using that file.

https://unicode-org.atlassian.net/browse/ICU-20697

**Comment by sffc** [comment] 2020-06-10 04:59
> Similarly, do you know if there's any intention to have an uloc_openAvailableByType equivalent for Collator use?

The data is present in ICU 65+, but you need to use some manual data access APIs to get at it. I can share an example if you would like.

> Also I believe it may be too naive to assume that an alias will exist for `xx-ZZ` just because `xx-Yyyy-ZZ` exists?
> 
> For instance, [ICU4C](https://github.com/unicode-org/icu/tree/master/icu4c/source/data/locales) has the following Fulah locales...
> 
> ```
> ff
> ff-{Adlm, Latn}
> ff-{Adlm, Latn}-{BF, CM, GH, GM, GN, GW, LR, MR, NE, NG, SL, SN}
> ff-{CM, GN, MR, SN}
> ```
> 
> ...which is to say that it lacks aliases `ff-{BF, GH, GM, GW, LR, NE, NG, SL}`.
> 
> (Edit: I guess the same is true of the aforementioned `sr-ME`.)

It's all about the fallback chain. If there is no data file for a particular LSR (language-script-region), then the fallback is the locale with the last subtag stripped off. For example, zh-GB would fall back to zh, which is Hans. However, the data files can override the fallback, such that zh-TW falls back to zh-Hant-TW, as stated in zh_TW.txt.

In the Fulani example, that language is written in three scripts (Arab, Latn, Adlm), with Arab as the default. So, ff-BF falls back to ff, which is Arab script, but if the script is explicitly requested by the user, such as ff-Adlm-BF, then they get the Adlm version.

It's still not clear to me how the 402 spec can really be improved in this area.

**Comment by rkirsling** [comment] 2020-06-12 19:27
Based on the above, I've [updated](https://bugs.webkit.org/show_bug.cgi?id=213007) JSC to ensure we have an LR locale for all available LSR locales.

I guess going this route fixes a bunch of long-standing oddities, e.g., `yue-CN` now resolves as `Hans`.

And if this is the intended reading of the current spec text, I do think we should clarify it as an "all" instead of an unguessable "some".

**Comment by sffc** [comment] 2020-06-18 21:49
FYI: here's a PR to remove the icu-locale-deprecates.xml file from ICU: https://github.com/unicode-org/icu/pull/1181

**Comment by hagbard** [comment] 2020-06-19 12:19
Removing it because it's now done elsewhere using the new LDML conversion tooling, not because the ICU data being generated is changing.

See:
https://github.com/unicode-org/icu/blob/master/tools/cldr/cldr-to-icu/build-icu-data.xml#L104
and the following sections for details.

**Comment by sffc** [comment] 2020-09-10 21:05
Notes from 2020-07-09 TC39-TG2 meeting:

https://github.com/tc39/ecma402/blob/master/meetings/notes-2020-07-09.md#old-style-language-tags-is-too-vague

@rkirsling Would you be interested in taking this issue and proposing any necessary spec changes?

**Comment by rkirsling** [comment] 2020-09-10 22:59
@sffc Can do!

**Closed** 2021-01-04 23:51 UTC
Labels: Editorial, c: locale, s: help wanted, web reality
