### ISSUE TITLE
Locale object with custom `toString()` is silently ignored when not wrapped in an array in DateTimeFormat constructor

### ISSUE THREAD

**Issue by justingrant** [tc39/ecma402#591] opened 2021-07-13 02:36 UTC
When a built-in object's method expects a string-valued parameter but an object is passed, usually `toString()` is called on that object. For example, when calling `new Intl.DateTimeFormat([foo], { hour: bar })`, if `foo` and `bar` are objects then their `toString()` will be called and the objects will be coerced to strings.

But this behavior doesn't work when a non-array-like object is used value is used as the first (`locales`) parameter of the constructor of `Intl.DateTimeFormat`.  If you wrap the object in an array, it works fine.

My main concern is that the failure is silent: there's no error shown to the user, but the user's desired locale is not used. 

Should the spec be changed in the future to either of the following behaviors?
* A) throw an exception, which would clearly show developers that these kinds of exotic objects are disallowed without being array-wrapped
OR 
* B) Coerce these objects to strings.

Honestly I wasn't sure if either of above are technically possible, but I figured this was surprising enough behavior that it was worth filing an issue to discuss with 402 experts.

Here's some repro cases.

```js
// Array locales work OK
new Intl.DateTimeFormat([{ toString: () => 'ja-JP' } ]).resolvedOptions().locale
// expected and actual: "ja-JP"

// options work OK
new Intl.DateTimeFormat('en-US', { month: { toString: () => 'short' } } ).resolvedOptions().month
// expected and actual: "short"

// non-Array locales don't work
new Intl.DateTimeFormat({ month: { toString: () => 'short' } }).resolvedOptions().locale
// expected: "ja-JP"
// actual: "en-US"
```

**Comment by justingrant** [comment] 2021-07-13 02:37
BTW, the relevant part of the 402 spec is here: https://tc39.es/ecma402/#sec-canonicalizelocalelist

**Comment by anba** [comment] 2021-07-13 11:16
This is kind of the standard behaviour for [array-like objects](https://tc39.es/ecma262/#sec-lengthofarraylike), similar to how `Array.from({})` returns an empty array and _silently_ discards the input object.

Apart from that, I don't think leading optional parameters are common, so somehow interpreting the first argument as the options object in certain contexts doesn't excite me too much.

**Comment by jswalden** [comment] 2021-07-13 22:43
Yeah.  There really isn't a good way to distinguish object-that-stringifies, from object-that's-arraylike.  The choice is somewhat arbitrary, and if we're doing what other places do -- and moreover, what has been the specified behavior since these interfaces were defined -- I can't see a reason to change.

**Comment by justingrant** [comment] 2021-07-14 00:59
> Yeah. There really isn't a good way to distinguish object-that-stringifies, from object-that's-arraylike. The choice is somewhat arbitrary, and if we're doing what other places do -- and moreover, what has been the specified behavior since these interfaces were defined -- I can't see a reason to change.

@jswalden Yep, that's what I kinda expected. This use case is pretty obscure so I don't see a big problem leaving it unfixed.

Thanks for taking a look at this.  The fact that this is unlikely to change makes the Temporal polyfill a little easier now. :-)

> Apart from that, I don't think leading optional parameters are common, so somehow interpreting the first argument as the options object in certain contexts doesn't excite me too much.

@anba Sorry, I wasn't suggesting that the first parameter should be optional. Instead, I'm suggesting that the first parameter should always be considered a locale, but there should be some fallback if the object isn't array-like for it to be stringified... or an exception should be thrown. Sounds like per @jswalden this is not practical, though.

If y'all don't think that the current design needs to change, feel free to close this issue.

**Comment by ryzokuken** [comment] 2021-07-22 05:04
Looks like there is some general agreement here that things work as intended, so I am closing this. Please feel free to reopen if you disagree or something changes.

**Closed by ryzokuken** 2021-07-22 05:04 UTC
Labels: c: locale, s: discuss
