### ISSUE TITLE
Intl.DateTimeFormat.prototype.formatRange and time only range display

### ISSUE THREAD

**Issue by cutterbl** [tc39/ecma402#860] opened 2024-02-13 20:47 UTC
Consider the following:
```
const date = new Date(2020, 11, 20, 3, 23, 16, 738);
const date2 = new Date(2020, 11, 22, 13, 35, 16, 738);

console.log(new Intl.DateTimeFormat('en-US', {
  hour: '2-digit',
  minute: '2-digit'
}).formatRange(date, date2));
```
My expected output here would be `03:23 AM – 01:35 PM`, but what I receive is `12/20/2020, 3:23 AM – 12/22/2020, 1:35 PM`

**Comment by sffc** [comment] 2024-02-13 21:17
The problem is that your times are on different dates. `formatRange` won't elide the date unless the dates are the same on both sides of the range separator. This is the behavior defined in the specification:

https://tc39.es/ecma402/#sec-partitiondatetimerangepattern

Closing as Works As Intended

**Closed by sffc** 2024-02-13 21:17 UTC

**Comment by ptomato** [comment] 2024-02-13 22:19
Note that what you want will be possible with Temporal:
```js
const dt = new Temporal.PlainDateTime(2020, 12, 20, 3, 23, 16, 738);
// => Temporal.PlainDateTime <2020-12-20T03:23:16.738>
const dt2 = new Temporal.PlainDateTime(2020, 12, 22, 13, 35, 16, 738);
// => Temporal.PlainDateTime <2020-12-22T13:35:16.738>
new Intl.DateTimeFormat('en-US').formatRange(dt.toPlainTime(), dt2.toPlainTime())
// => '3:23:16 AM – 1:35:16 PM'
```

**Comment by cutterbl** [comment] 2024-02-14 02:09
@sffc @ptomato Thank you both for responding. @sffc That makes complete sense. Not sure how I missed it. Retesting with same date works perfect. @ptomato That's good to know. So looking forward to Temporal.
