### ISSUE TITLE
FormatNumberToString doesn't handle negative/non-finite numbers

### ISSUE THREAD

**Issue by Ms2ger** [tc39/ecma402#261] opened 2018-08-23 12:27 UTC
`FormatNumberToString` is documented as taking any Number value, but it immediately calls     `ToRawPrecision` or `ToRawFixed`, each of which expects a finite non-negative number. 

It turns out there is indeed a path that calls it with (finite) negative numbers: Intl.PluralRules.prototype.select → ResolvePlural → FormatNumberToString.

This is already fixed in the [Intl.NumberFormat Unified API Proposal](https://github.com/sffc/proposal-unified-intl-numberformat/commit/cc2ed3df413b722af1332470a9b81b52718f774a).

Relevant changes: https://github.com/tc39/ecma402/pull/104, https://github.com/tc39/proposal-intl-plural-rules/pull/15.

**Comment by littledan** [comment] 2018-10-14 09:34
If anyone wants to break that change out and make a PR here, it'd be welcome. Otherwise, I think we can wait for the Unified API Proposal to land the fix.

**Comment by sffc** [comment] 2020-03-20 21:51
Confirmed that the abstract operation `FormatNumberToString` is no longer called with a NaN or Infinity value, since Unified NumberFormat has been checked-in.  Closing as Fixed.

**Closed by sffc** 2020-03-20 21:51 UTC
Labels: c: numbers, s: active proposal
