### ISSUE TITLE
Compact number in PluralRules (CLDRv38)

### ISSUE THREAD

**Issue by longlho** [tc39/ecma402#529] opened 2021-01-07 03:30 UTC
CLDRv38 introduced `c`/`e` operand to deal with compact numbers (e.g French). This basically handles `1e7` differently from `10000000`.

Right now `select` calls `ToNumber` on the argument which effectively lost the compact operand.

I assume `GetOperands` need to be updated as well.

References:
https://github.com/formatjs/formatjs/issues/2482
https://github.com/eemeli/make-plural/pull/23

**Comment by zbraniecki** [comment] 2021-01-07 03:49
I'm not sure if it does. ECMA-402 does not define the data model for the input data - https://tc39.es/ecma402/#sec-intl.pluralrules-internal-slots

The use of CLDR is a implementation detail. We do look up to CLDR as a reference database, but I don't think there's anything in the specification that needs to be updated in this case.

**Comment by longlho** [comment] 2021-01-07 03:54
Yes I understand that it is an implementation detail and the spec is best effort. I think this would be an enhancement to the spec to handle cases like `1e7` separately. Right now the spec explicitly prohibits it bc of `ToNumber` usage and a spec-compliant implementation cannot even do it itself even if it wants to. I'm proposing to change the spec to allow this.

**Comment by zbraniecki** [comment] 2021-01-07 03:59
> Yes I understand that it is an implementation detail and the spec is best effort. I think this would be an enhancement to the spec to handle cases like 1e7 separately. Right now the spec explicitly prohibits it bc of ToNumber usage and a spec-compliant implementation cannot even handle it by itself even if it wants to. I'm proposing to change the spec to allow this.

I'm wondering if it should be within PluralRules, or `ToNumber` really. I think it would be weird if we handled `1e7` in PluralRules, but not in `NumberFormat`.

And to get it across the board, we may need a more comprehensive review of string to number in ECMA402 (and maybe even ECMA-262?)

**Comment by longlho** [comment] 2021-01-07 04:08
I also wants to call out there's a decent amount of potential logic overlap with NumberFormat scientific notation format when used in conjunction with units (e.g `1e3 bytes`). NumberFormat handles parsing of `1e3` separately into `1` & `3` and invoke plural rules selection accordingly.

Therefore I actually don't know if it's necessarily a `ToNumber` issue or PluralRules select is supposed to take a different input semantic?

On the same note, currently there's also a conflation between `1` & `1.000`, which potentially can result in different plural rule selection.

cc @srl295 for more context if necessary.

**Comment by sffc** [comment] 2021-01-07 09:01
Duplicate of #399.  Intl.PluralRules should have a "notation" option like Intl.NumberFormat that makes it follow the same semantics, as required by UTS 35.

I don't advocate for making Intl.PluralRules interpret a string input any different than Intl.NumberFormat interprets a string input: the string gets cast to a number.  The way to get the proper CLDR behavior is to use the notation option.

**Closed by sffc** 2021-01-07 09:01 UTC
