### ISSUE TITLE
BigInt.prototype.toLocaleString

### ISSUE THREAD

**Issue by littledan** [tc39/ecma402#218] opened 2018-02-14 19:50 UTC
In the Stage 3 [BigInt](https://github.com/tc39/proposal-bigint/) proposal, [toLocaleString](https://tc39.github.io/proposal-bigint/#sec-bigint.prototype.tolocalestring) is defined. We should have a definition for this in the ECMA-402 specification.

I wasn't able to find an ICU API which would be useful here; does one exist?

cc @jakobkummerow

**Comment by anba** [comment] 2018-03-06 13:57
ICU4C has `unum_formatDecimal`, ICU4J has `NumberFormat#format(java.math.BigInteger)`.

**Comment by littledan** [comment] 2018-03-06 16:20
That looks perfect for this case. Seems like we could pass the output of ToString(bigInt) to `unum_formatDecimal` as its number/length arguments, if I'm understanding the [Decimal Arithmetic Specification](http://speleotrove.com/decimal/daconvs.html) correctly.

@anba Would you be interested in writing specification text for  BigInt.prototype.toLocaleString in ECMA 402? The design I was imagining would be to base it on an overload of Intl.NumberFormat.prototype.format for BigInts--[Number Format Functions](https://tc39.github.io/ecma402/#sec-number-format-functions) could start with ToNumeric rather than ToNumber, and then [PartitionNumberPattern](https://tc39.github.io/ecma402/#sec-partitionnumberpattern) would somehow be either generalized or cloned to handle BigInt in addition to Number.

cc @cxielarko

**Comment by anba** [comment] 2018-03-15 15:48
AFAICT the descriptions for `FormatNumberToString`, `PartitionNumberPattern`, `FormatNumber`, `ToRawPrecision`, and `ToRawFixed` only need to be changed to allow BigInt values for the `x` parameter. `BigInt.prototype.toLocaleString` can then be defined as:
 1. Let _x_ be ? thisBigIntValue(*this* value).
 1. Let _numberFormat_ be ? Construct(%NumberFormat%, &laquo; _locales_, _options_ &raquo;).
 1. Return FormatNumber(_numberFormat_, _x_).

And maybe `s/Number/Numeric/` for `FormatNumberToString`, `PartitionNumberPattern`, and `FormatNumber`?

Do we also want to modify (or add a new method) to allow BigInt values for `Intl.NumberFormat.prototype.format` and `Intl.NumberFormat.prototype.formatToParts`? The latter may not be implementable in ICU4C because it lacks a `unum_formatDecimalForFields` function.

**Comment by sffc** [comment] 2018-03-16 04:57
FYI, better than `unum_formatDecimal` and `NumberFormat#format(java.math.BigInteger)` is to use the new methods offered in icu.number and numberformatter.h.  The former two methods are not deprecated (at least not yet), but they are discouraged for new users.

numberformatter.h has an endpoint for the same syntax as `unum_formatDecimal`, but it also has full support for the field position iterator needed for `formatToParts`.  You use it like this:

```cpp
FormattedNumber result = NumberFormatter::withLocale(...).formatDecimal(...);
result.populateFieldPositionIterator(...);
UnicodeString resultString = result.toString();
```

**Comment by anba** [comment] 2018-03-16 11:30
Thanks for the info that the new number formatting API will support this use case! For SpiderMonkey we may need to wait for https://ssl.icu-project.org/trac/ticket/13597, because we generally only use the C-API for its compatibility across different releases.

**Comment by sffc** [comment] 2018-04-20 19:06
As a general comment, I think that we should interpret string inputs as the highest precision datatype supported.  So if I give a string containing something like "987654321987654321987654321", that should be interpreted as a BigInteger.  However, "9876.543" should be interpreted as a double until Ecma adds a datatype for BigDecimal, for example.

**Comment by littledan** [comment] 2018-04-21 14:28
I'd prefer not to do this sort of "magical" semantic overloading. If your intuition is that that should exist, then I'm inclined to add another method, and avoid overloading, e.g., Intl.NumberFormat.prototype.formatBigInt/formatBigIntToParts. What would you think of that?

**Comment by sffc** [comment] 2018-04-22 00:26
I don't see this as "magical" overloading.  I see it as the method taking the input data type and then internally choosing the highest precision data type available to represent it.

My intuition is that it's weird to ever convert strings to Numbers, and we should avoid it when possible with better alternative behavior.

**Comment by littledan** [comment] 2018-04-24 19:39
> My intuition is that it's weird to ever convert strings to Numbers, and we should avoid it when possible with better alternative behavior.

Following this intuition, I'd like to mentally classify the `format` method accepting String arguments at all as weird random legacy behavior, and based on that analysis, *not* upgrade it to get higher precision. We can't remove it, but we also don't have to improve it. Leaving `format(String)`'s behavior unchanged will simplify the specification and implementation.

**Comment by FrankYFTang** [comment] 2019-01-19 00:01
Could someone show me a js example code of how to use BigInt with the toLocaleString?

IS it like

12345678901234567890n.toLocaleString("zh", {style: "compact"})

?
Is it adding a "n" after the digit good enough to denote the BigInt? Sorry of my confidence of knowing BigInt well here.

**Comment by FrankYFTang** [comment] 2019-01-25 04:31
Thanks for the code review from @jakobkummerow the v8 implementation sync with the current spec ( 040f809 ) is landed into v8 tree behind the flag --harmony-intl-bigint . You can also see the test I wrote here
https://chromium-review.googlesource.com/c/v8/v8/+/1424021/8/test/intl/bigint/tolocalestring.js
Notice in this implementation BigInt(-0).toLocaleString() will output "0" instead of "-0". @jakobkummerow said that is the expected behavior. In the other hand (-0).toLocaleString() will return "-0".

**Comment by littledan** [comment] 2019-01-25 10:08
Great work, @FrankYFTang !

That's right; for BigInt, `-0n` is `0n`.

I'm going to present on this issue in the upcoming TC39 meeting, arguing we should instead make a separate method, `formatBigInt`, and consider that a pattern going forward. See [slides](https://docs.google.com/presentation/d/11A3MSCUv9XEkquWPaCl3GkksI4v5bhZOMSe5r5Aj_uw/edit#slide=id.p).

**Comment by ray007** [comment] 2019-01-25 12:03
I can understand there being a difference between `-0` and `0` for double/float, but for integers?

**Comment by FrankYFTang** [comment] 2019-01-25 19:39
The reason my current v8 implementation output BigInt(-0) to "0" is because the BitInt.prototype.toString output "0" instead of "-0".

**Closed** 2019-06-13 17:26 UTC
Labels: c: numbers, s: active proposal
