### ISSUE TITLE
Allow passing in string to `NumberFormat.prototype.format()`

### ISSUE THREAD

**Issue by mwgamble** [tc39/ecma402#407] opened 2020-02-10 01:30 UTC
It would be great to be able to pass in a string in the format `\d+\.\d*` (or something along those lines) and have the number formatter work with it. Right now there's no support for very large numbers, either from `BigInt` or from a third-party "big number" library like `bignumber.js`. At the very least, the latter provides functionality to retrieve the full precision number in a non-locale-dependent string form, which should be perfect for passing in to the number formatter.

**Comment by sffc** [comment] 2020-02-26 05:25
@littledan added BigInt formatting support in #236.  He is also championing [a Stage 1 proposal for high-precision decimals](https://github.com/tc39/proposal-decimal).  Those proposals should cover most of the bases.

That being said, a smaller feature which could serve this use case would be a `scale` option that multiplies the number by a power of 10 before formatting.  Combined with BigDecimal, you can then format any arbitrary precision number.

**Comment by mwgamble** [comment] 2020-02-26 22:31
I don't understand why it all needs to be that complicated. Based on my review of a prominent polyfill, the very first thing the code does is cast the number to a string anyway. It therefore follows that it should be easy to just accept strings directly.

**Comment by sffc** [comment] 2020-02-26 23:52
There are several problems with accepting strings as part of the spec:

1. We already accept strings (they are cast to Number and lose precision).  Treating strings as high-precision decimals would be a breaking change.
2. This would introduce a new syntax surface that we need to support.  I'm not aware of anywhere in ECMA-262 or ECMA-402 that currently uses the `\d+(.\d+)(E\d+)?` scientific decimal notation.  If we start accepting that in Intl.NumberFormat, we will have to put that in front of TC39 and make a conscious decision to start accepting that format as the de-facto decimal string serialization syntax.

Better would be if we had a first-class ECMAScript type for high-precision decimals, which is what @littledan's proposal does, and as a fallback, the BigInt+scale approach gets the job done and is not too bad.

**Comment by hbgl** [comment] 2020-03-06 04:56
@sffc 

About 1.
A new option could be added to treat the argument as a decimal string. 

That being said, I like the BigInt+scale approach better.

**Comment by sffc** [comment] 2020-03-20 23:39
Closing as a dupe of #334

**Closed by sffc** 2020-03-20 23:39 UTC
Labels: c: numbers, s: help wanted, small
