### ISSUE TITLE
Add unanchored intervals

### ISSUE THREAD

**Issue by ByteEater-pl** [tc39/ecma402#322] opened 2019-02-13 04:38 UTC
The IntervalFormat issue postulates an API for creating strings like "3—5 May 2022". There's also a proposal for instances specified relatively, e.g. "two years and five days ago", "in 1 hour, 2 minutes and 1 second". There's a simpler and also commonly needed case that's missing: just "2 days", "two years and five days", "1 hour, 2 minutes and 1 second" (no "ago" or "in").

**Comment by sffc** [comment] 2019-02-13 07:09
> The IntervalFormat issue postulates an API for creating strings like "3—5 May 2022". There's also a proposal for instances specified relatively, e.g. "two years and five days ago", "in 1 hour, 2 minutes and 1 second".

This is actually implemented in a different Stage 3 proposal:

https://github.com/tc39/proposal-intl-relative-time

> There's a simpler and also commonly needed case that's missing: just "2 days", "two years and five days", "1 hour, 2 minutes and 1 second" (no "ago" or "in").

This is covered by unit formatting:

https://github.com/tc39/proposal-unified-intl-numberformat

When combining multiple such units, you can use Intl.ListFormat:

https://github.com/tc39/proposal-intl-list-format

**Comment by ByteEater-pl** [comment] 2019-02-13 12:02
> This is actually implemented in a different Stage 3 proposal:
>
> https://github.com/tc39/proposal-intl-relative-time
That's what I was referring to.

> This is covered by unit formatting
> When combining multiple such units, you can use Intl.ListFormat
These are separate features. What this issue is about is a combination of both specialized for time intervals. E.g. programmers shouldn't need to know the list of units involved. (I imagine one in 59 s, two in 61 s and possibly one or two, depending on an option, in 1.5 s. The number of units used may even be, especially for factions, locale dependent.)

I also take back the "two years and five days" example. I recalled the distinction in the SQL standard between year-month and day-time intervals which cannot be mixed (since months differ in number of days) and it occurred to me that ECMAScript should follow suit.

**Comment by littledan** [comment] 2019-02-28 05:02
There was some past discussion about DurationFormat, I think. Is this subsumed by unit formatting? I thought some formats for durations were not, e.g., time remaining watching a video, but the cases that this issue starts with may fit into the same larger framework.

As for a high level API that removes the need for computations: we are generally focused on starting with low-level APIs here, to give application developers the most flexibility.

**Comment by sffc** [comment] 2019-02-28 08:05
Good point.  Numeric durations are supported in ICU MeasureFormat (internally the implementation is a bit of a hacky wrapper around DateFormat), but not in the proposals I listed previously.

**Comment by sffc** [comment] 2019-02-28 08:08
FWIW, I might support a feature like `formatDuration` on Intl.DateTimeFormat to support this, where that function always uses the numeric format (hh:mm:ss localized as needed).  The non-numeric formats for durations (5h 10m 13s) can continue to go through the Intl.ListFormat+Intl.NumberFormat code path suggested above.

**Comment by sffc** [comment] 2019-03-19 09:41
Closing this as a duplicate of #47

**Closed by sffc** 2019-03-19 09:41 UTC
