### ISSUE TITLE
Can we change the Intl prototypes to be normal objects?

### ISSUE THREAD

**Issue by anba** [tc39/ecma402#122] opened 2017-01-23 18:20 UTC
From https://bugzilla.mozilla.org/show_bug.cgi?id=1332604:

Intl.prototype.{Collator, DateTimeFormat, NumberFormat} are currently spec'ed as being instances of Intl.{Collator, DateTimeFormat, NumberFormat} (cf. 10.3, 11.4, 12.4). We should consider changing them to normal objects similar to how Date.prototype was changed to a normal object in the ECMAScript specification for ES6. 

This change should be web-compatible because V8 already treats the prototype objects as normal objects.

**Comment by zbraniecki** [comment] 2017-01-24 22:12
@caridy , @domenic , @littledan, @jungshik

**Comment by littledan** [comment] 2017-02-10 14:09
Yep, let's do it!

**Comment by littledan** [comment] 2017-02-10 14:10
cc other implementations @jswalden @thetalecrafter @bterlson

**Comment by thetalecrafter** [comment] 2017-02-10 15:52
`Intl.NumberFormat.prototype.format(1234.5)` currently throws in V8, but returns `"1,234.5"` in JSC. iirc, I interpreted the v2 spec to mean that the prototype object is a _properly initialized_ Intl.* object.

Given that it currently throws in V8, I'd be really surprised if there is code in the wild that relies on JSC's current behavior. I think it would be good to have the prototypes be plain objects.

I'm willing to make the change in JSC once the spec change is approved.

**Comment by thetalecrafter** [comment] 2017-02-11 19:41
I did a quick pass at what the implications of this change might include:

Referencing `Intl.Collator.prototype.compare`, `Intl.{DateTime,Number}Format.prototype.{format,formatToParts}`, will throw an error. I think this makes sense, since they are defined as getters meant to be called on a properly initialized Intl object.

It's possible there is an expectation to be able to do `Intl.Collator.prototype.compare.call(someCollator, a, b)`, but the spec has always been for getters of bound functions, so it wouldn't have used `comeCollator`'s options anyway. This does make the change a little less analogous to `Date.prototype`, though.

Calling `Intl.*.prototype.resolvedOptions()` will throw an error. The only use case I could see, is to try to get the base defaults, which you can already do by creating an `Intl.*` object without passing any arguments.

**Comment by thetalecrafter** [comment] 2017-02-11 22:40
https://bugs.webkit.org/show_bug.cgi?id=168178

**Comment by rwaldron** [comment] 2017-06-28 16:20
@ericf ping

**Comment by caridy** [comment] 2017-08-10 16:18
@thetalecrafter it seems that your ticked was resolved.

I will like to bring this up in the next meeting, and try to get consensus to merge #148. I wonder what's @bterlson's position considering that Chakra is not throwing for `Intl.NumberFormat.prototype.format(1234.5)`.

**Comment by thetalecrafter** [comment] 2017-08-10 16:52
@caridy Yeah the ticket was closed in April. The change is in the current technology preview and should be in Safari 11.

**Comment by rwaldron** [comment] 2017-08-10 19:41
@caridy Is this no longer an issue in Intl.js?

**Comment by caridy** [comment] 2017-08-10 20:52
@rwaldron it is not longer an issue there:

```
> Intl.NumberFormat.prototype.format(1234.5)
TypeError: `this` value for format() is not an initialized Intl.NumberFormat object.
    at NumberFormatConstructor.GetFormatNumber (/Users/cpatino/repo/Intl.js/lib/core.js:2431:70)
    at repl:1:28
```

**Comment by caridy** [comment] 2017-08-10 20:59
I have confirmed that V8, SpiderMonkey, Intl.js and JSC (technology preview) are aligned with this. I have opened the [issue for ChakraCore](https://github.com/Microsoft/ChakraCore/issues/3513) as instructed by @bterlson for the fix.

It seems that we are all in agreement.

**Comment by leobalter** [comment] 2017-08-23 17:56
Do we need to bring this to the meeting or are we all set here? We have tests ready to land.

**Comment by littledan** [comment] 2017-08-23 18:33
Sounds like it's ready for @caridy to land. The tests can be landed once the spec patch is landed.

**Comment by littledan** [comment] 2017-08-23 18:34
I merged the PR based on the consensus that @caridy mentioned above, so tests should be good to land.

**Closed** 2017-08-23 18:34 UTC
Labels: question, Spec Maintenance, web reality
